name: bikerider
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  http: ^0.13.5
  google_fonts: ^3.0.1
  provider: ^6.0.4
  animated_splash_screen: ^1.3.0
  image_picker: ^0.8.6
  smooth_page_indicator: ^1.0.0+2
  otp_text_field: ^1.1.3
  flutter_bloc: ^8.1.1
  fluttertoast: ^8.1.1
  dropdown_textfield: ^1.0.6
  dio: ^4.0.6
  flutter_secure_storage: ^6.0.0
  auto_size_text_field: ^2.1.0
  emoji_picker_flutter: ^1.5.0
  intl: ^0.17.0
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  flutter_contacts: ^1.1.5+1
  geolocator: ^9.0.2
  flutter_google_places: ^0.3.0
  google_maps_flutter: ^2.2.1
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0
  url_launcher: ^6.1.6
  flutter_rating_bar: ^4.0.1
  pdf: ^3.1.0
  dotted_line: ^3.1.0
  flutter_staggered_grid_view: ^0.6.2
  infinite_scroll_pagination: ^3.2.0
  gallery_saver: ^2.3.2
  image_gallery_saver: ^1.7.1
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/user.png
    - assets/images/
    - assets/images/login/
    - assets/images/register/
    - assets/images/ownbike/
    - assets/images/splash/
    - assets/images/tutorial/
    - assets/images/chooseavatar/
    - assets/images/reset/
    - assets/images/homePage/
    - assets/images/Temp/
    - assets/images/homePage/bottom_navigation/
    - assets/images/homePage/garage_images/
    - assets/images/create_trip/
    - assets/images/search/
    - assets/images/contacts/
    - assets/images/google_maps/
    - assets/images/Chat/
    - assets/images/trip_summary/
    - assets/images/manual/
    - assets/images/trip_start/
    - assets/images/book_service/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
